# render.yaml en la raíz de tu proyecto
services:
  # Servicio del Backend Node.js
  - type: web
    name: padel-club-backend # Nombre para tu servicio backend en Render
    env: node # Tipo de entorno
    rootDir: server # Carpeta de tu backend dentro del repositorio
    buildCommand: 'npm install' # Comando para instalar dependencias del backend
    startCommand: 'npm start' # Comando para iniciar el servidor
    plan: free # Plan gratuito (se suspende por inactividad). Puedes cambiar a 'starter' si lo necesitas activo 24/7.
    healthCheckPath: '/api/status' # Ruta para que Render verifique que el backend está vivo
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001 # El puerto que usará Render (interno)
      # Las variables sensibles se añadirán manualmente en el dashboard de Render por seguridad
      # No se incluyen aquí directamente por buenas prácticas.